// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBq7-QCldoQ4vSTNJ3OI68hiiopZQYkAM',
    appId: '1:571434598148:web:661a35dc52c0d227a6da51',
    messagingSenderId: '571434598148',
    projectId: 'fire-auth-system-f4794',
    authDomain: 'fire-auth-system-f4794.firebaseapp.com',
    storageBucket: 'fire-auth-system-f4794.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5mjc8rnE2HbwwBCjyN_zjwX_oINeXXfI',
    appId: '1:571434598148:android:764c586c37050b90a6da51',
    messagingSenderId: '571434598148',
    projectId: 'fire-auth-system-f4794',
    storageBucket: 'fire-auth-system-f4794.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBREJywWrP6e9WP4PAtVHACwa3WRcuGCpY',
    appId: '1:571434598148:ios:b0a10ae09368895ca6da51',
    messagingSenderId: '571434598148',
    projectId: 'fire-auth-system-f4794',
    storageBucket: 'fire-auth-system-f4794.firebasestorage.app',
    iosClientId: '571434598148-ab5hitgslhorr34hbbke8ccmpedfhpte.apps.googleusercontent.com',
    iosBundleId: 'com.example.auth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBREJywWrP6e9WP4PAtVHACwa3WRcuGCpY',
    appId: '1:571434598148:ios:b0a10ae09368895ca6da51',
    messagingSenderId: '571434598148',
    projectId: 'fire-auth-system-f4794',
    storageBucket: 'fire-auth-system-f4794.firebasestorage.app',
    iosClientId: '571434598148-ab5hitgslhorr34hbbke8ccmpedfhpte.apps.googleusercontent.com',
    iosBundleId: 'com.example.auth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBq7-QCldoQ4vSTNJ3OI68hiiopZQYkAM',
    appId: '1:571434598148:web:f95afb4af68f513ea6da51',
    messagingSenderId: '571434598148',
    projectId: 'fire-auth-system-f4794',
    authDomain: 'fire-auth-system-f4794.firebaseapp.com',
    storageBucket: 'fire-auth-system-f4794.firebasestorage.app',
  );
}
